run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
      - name: indent-error-flow
      - name: errorf
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter
      - name: var-declaration
  goimports:
    local-prefixes: github.com/waffo-com/waffo-pancake-sdk-go

issues:
  exclude-dirs:
    - examples
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
